////////////////////////////////////////////////////////////////////////////////
//
//  Licensed to the Apache Software Foundation (ASF) under one or more
//  contributor license agreements.  See the NOTICE file distributed with
//  this work for additional information regarding copyright ownership.
//  The ASF licenses this file to You under the Apache License, Version 2.0
//  (the "License"); you may not use this file except in compliance with
//  the License.  You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.
//
////////////////////////////////////////////////////////////////////////////////
public var dataGridData:Array = [
		{ EmpName:'E1', Department:'D1', EmpCode:1, Rating:'1' },
		{ EmpName:'E2', Department:'D1', EmpCode:2, Rating:'4' },
		{ EmpName:'E3', Department:'D1', EmpCode:3, Rating:'3' },
		{ EmpName:'E4', Department:'D1', EmpCode:4, Rating:'5' },
		{ EmpName:'E4', Department:'D1', EmpCode:5, Rating:'2' },
		{ EmpName:'E3', Department:'D1', EmpCode:6, Rating:'3' },
		{ EmpName:'E2', Department:'D1', EmpCode:7, Rating:'2' },
		{ EmpName:'E1', Department:'D1', EmpCode:8, Rating:'4' },
		{ EmpName:'E1', Department:'D1', EmpCode:9, Rating:'3' },
		{ EmpName:'E2', Department:'D1', EmpCode:10, Rating:'4' },
		{ EmpName:'E3', Department:'D1', EmpCode:11, Rating:'2' },
		{ EmpName:'E4', Department:'D1', EmpCode:12, Rating:'4' },
		{ EmpName:'E4', Department:'D1', EmpCode:13, Rating:'3' },
		{ EmpName:'E3', Department:'D1', EmpCode:14, Rating:'3' },
		{ EmpName:'E2', Department:'D1', EmpCode:15, Rating:'1' },
		{ EmpName:'E1', Department:'D1', EmpCode:16, Rating:'2' },
		{ EmpName:'E1', Department:'D1', EmpCode:17, Rating:'2' },
		{ EmpName:'E2', Department:'D1', EmpCode:18, Rating:'1' },
		{ EmpName:'E3', Department:'D1', EmpCode:19, Rating:'1' },
		{ EmpName:'E4', Department:'D2', EmpCode:20, Rating:'3' },
		{ EmpName:'E4', Department:'D2', EmpCode:21, Rating:'1' },
		{ EmpName:'E3', Department:'D2', EmpCode:22, Rating:'2' },
		{ EmpName:'E2', Department:'D2', EmpCode:23, Rating:'1' },
		{ EmpName:'E1', Department:'D2', EmpCode:24, Rating:'1' },
		{ EmpName:'E1', Department:'D2', EmpCode:25, Rating:'4' },
		{ EmpName:'E2', Department:'D2', EmpCode:26, Rating:'4' },
		{ EmpName:'E3', Department:'D2', EmpCode:27, Rating:'3' },
		{ EmpName:'E4', Department:'D2', EmpCode:28, Rating:'3' },
		{ EmpName:'E4', Department:'D2', EmpCode:29, Rating:'1' },
		{ EmpName:'E3', Department:'D3', EmpCode:30, Rating:'1' },
		{ EmpName:'E2', Department:'D3', EmpCode:31, Rating:'1' },
		{ EmpName:'E1', Department:'D3', EmpCode:32, Rating:'2' },
		{ EmpName:'E5', Department:'D3', EmpCode:33, Rating:'2' },
		{ EmpName:'E1', Department:'D3', EmpCode:34, Rating:'2' },
		{ EmpName:'E2', Department:'D3', EmpCode:35, Rating:'1' },
		{ EmpName:'E3', Department:'D3', EmpCode:36, Rating:'4' },
		{ EmpName:'E4', Department:'D3', EmpCode:37, Rating:'3' },
		{ EmpName:'E4', Department:'D3', EmpCode:38, Rating:'4' },
		{ EmpName:'E3', Department:'D3', EmpCode:39, Rating:'1' },
		{ EmpName:'E2', Department:'D4', EmpCode:40, Rating:'1' },
		{ EmpName:'E1', Department:'D4', EmpCode:41, Rating:'1' },
		{ EmpName:'E1', Department:'D4', EmpCode:42, Rating:'3' },
		{ EmpName:'E2', Department:'D4', EmpCode:43, Rating:'1' },
		{ EmpName:'E3', Department:'D4', EmpCode:44, Rating:'3' },
		{ EmpName:'E4', Department:'D4', EmpCode:45, Rating:'4' },
		{ EmpName:'E4', Department:'D4', EmpCode:46, Rating:'4' },
		{ EmpName:'E3', Department:'D4', EmpCode:47, Rating:'2' },
		{ EmpName:'E2', Department:'D4', EmpCode:48, Rating:'1' },
		{ EmpName:'E1', Department:'D4', EmpCode:49, Rating:'1' },
		{ EmpName:'E1', Department:'D5', EmpCode:50, Rating:'3' },
		{ EmpName:'E2', Department:'D5', EmpCode:51, Rating:'3' },
		{ EmpName:'E3', Department:'D5', EmpCode:52, Rating:'3' },
		{ EmpName:'E4', Department:'D5', EmpCode:53, Rating:'3' },
		{ EmpName:'E4', Department:'D5', EmpCode:54, Rating:'1' },
		{ EmpName:'E3', Department:'D5', EmpCode:55, Rating:'4' },
		{ EmpName:'E2', Department:'D5', EmpCode:56, Rating:'4' },
		{ EmpName:'E1', Department:'D5', EmpCode:57, Rating:'3' },
		{ EmpName:'E1', Department:'D5', EmpCode:58, Rating:'4' },
		{ EmpName:'E2', Department:'D5', EmpCode:59, Rating:'1' },
		{ EmpName:'E3', Department:'D6', EmpCode:60, Rating:'2' },
		{ EmpName:'E4', Department:'D6', EmpCode:61, Rating:'2' },
		{ EmpName:'E4', Department:'D6', EmpCode:62, Rating:'2' },
		{ EmpName:'E3', Department:'D6', EmpCode:63, Rating:'1' },
		{ EmpName:'E2', Department:'D6', EmpCode:64, Rating:'4' },
		{ EmpName:'E1', Department:'D6', EmpCode:65, Rating:'3' },
		{ EmpName:'E1', Department:'D6', EmpCode:66, Rating:'3' },
		{ EmpName:'E2', Department:'D6', EmpCode:67, Rating:'4' },
		{ EmpName:'E3', Department:'D6', EmpCode:68, Rating:'4' },
		{ EmpName:'E4', Department:'D6', EmpCode:69, Rating:'1' },
		{ EmpName:'E4', Department:'D7', EmpCode:70, Rating:'2' },
		{ EmpName:'E3', Department:'D7', EmpCode:71, Rating:'2' },
		{ EmpName:'E2', Department:'D7', EmpCode:72, Rating:'4' },
		{ EmpName:'E1', Department:'D7', EmpCode:73, Rating:'1' },
		{ EmpName:'E1', Department:'D7', EmpCode:74, Rating:'3' },
		{ EmpName:'E2', Department:'D7', EmpCode:75, Rating:'3' },
		{ EmpName:'E3', Department:'D7', EmpCode:76, Rating:'1' },
		{ EmpName:'E4', Department:'D7', EmpCode:77, Rating:'1' },
		{ EmpName:'E4', Department:'D7', EmpCode:78, Rating:'1' },
		{ EmpName:'E3', Department:'D7', EmpCode:79, Rating:'4' },
		{ EmpName:'E2', Department:'D8', EmpCode:80, Rating:'4' },
		{ EmpName:'E1', Department:'D8', EmpCode:81, Rating:'4' },
		{ EmpName:'E1', Department:'D8', EmpCode:82, Rating:'4' },
		{ EmpName:'E2', Department:'D8', EmpCode:83, Rating:'4' },
		{ EmpName:'E3', Department:'D8', EmpCode:84, Rating:'1' },
		{ EmpName:'E4', Department:'D8', EmpCode:85, Rating:'1' },
		{ EmpName:'E4', Department:'D8', EmpCode:86, Rating:'1' },
		{ EmpName:'E3', Department:'D8', EmpCode:87, Rating:'2' },
		{ EmpName:'E2', Department:'D8', EmpCode:88, Rating:'2' },
		{ EmpName:'E1', Department:'D8', EmpCode:89, Rating:'1' },
		{ EmpName:'E1', Department:'D9', EmpCode:90, Rating:'4' },
		{ EmpName:'E2', Department:'D9', EmpCode:91, Rating:'4' },
		{ EmpName:'E3', Department:'D9', EmpCode:92, Rating:'1' },
		{ EmpName:'E4', Department:'D9', EmpCode:93, Rating:'3' },
		{ EmpName:'E4', Department:'D9', EmpCode:94, Rating:'3' },
		{ EmpName:'E3', Department:'D9', EmpCode:95, Rating:'3' },
		{ EmpName:'E2', Department:'D9', EmpCode:96, Rating:'1' },
		{ EmpName:'E1', Department:'D9', EmpCode:97, Rating:'1' },
		{ EmpName:'E2', Department:'D9', EmpCode:98, Rating:'4' },
		{ EmpName:'E3', Department:'D9', EmpCode:99, Rating:'1' },
		{ EmpName:'E4', Department:'D9', EmpCode:100, Rating:'2' }
		]