////////////////////////////////////////////////////////////////////////////////
//
//  ADOBE SYSTEMS INCORPORATED
//  Copyright 2009 Adobe Systems Incorporated
//  All Rights Reserved.
//
//  NOTICE: Adobe permits you to use, modify, and distribute this file
//  in accordance with the terms of the license agreement accompanying it.
//
////////////////////////////////////////////////////////////////////////////////

package spark.accessibility
{

import flash.accessibility.Accessibility;
import flash.events.Event;
import flash.events.FocusEvent;
import flash.utils.getQualifiedClassName;

import mx.accessibility.AccImpl;
import mx.accessibility.AccConst;
import mx.core.UIComponent;
import mx.core.mx_internal;
import mx.resources.IResourceManager;
import mx.resources.ResourceManager;

import spark.components.supportClasses.SliderBase;

use namespace mx_internal;

[ResourceBundle("components")]

/**
 *  SliderBaseAccImpl is a subclass of AccessibilityImplementation
 *  which implements accessibility for the SliderBase class.
 *
 *  @langversion 3.0
 *  @playerversion Flash 10
 *  @playerversion AIR 1.5
 *  @productversion Flex 4
 */
public class SliderBaseAccImpl extends AccImpl
{
    include "../core/Version.as";

    //--------------------------------------------------------------------------
    //
    //  Class methods
    //
    //--------------------------------------------------------------------------

    /**
     *  Enables accessibility in the SliderBase class.
     *
     *  <p>This method is called by application startup code
     *  that is autogenerated by the MXML compiler.
     *  Afterwards, when instances of sliders are initialized,
     *  their <code>accessibilityImplementation</code> property
     *  will be set to an instance of this class.</p>
     *
     *  @langversion 3.0
     *  @playerversion Flash 10
     *  @playerversion AIR 1.5
     *  @productversion Flex 4
     */
    public static function enableAccessibility():void
    {
        SliderBase.createAccessibilityImplementation =
            createAccessibilityImplementation;
    }

    /**
     *  @private
     *  Creates a SliderBase's AccessibilityImplementation object.
     *  This method is called from UIComponent's
     *  initializeAccessibility() method.
     */
    mx_internal static function createAccessibilityImplementation(
                                component:UIComponent):void
    {
        component.accessibilityImplementation =
            new SliderBaseAccImpl(component);
    }

    //--------------------------------------------------------------------------
    //
    //  Constructor
    //
    //--------------------------------------------------------------------------

    /**
     *  Constructor.
     *
     *  @param master The UIComponent instance that this AccImpl instance
     *  is making accessible.
     *
     *  @langversion 3.0
     *  @playerversion Flash 10
     *  @playerversion AIR 1.5
     *  @productversion Flex 4
     */
    public function SliderBaseAccImpl(master:UIComponent)
    {
        super(master);

        role = AccConst.ROLE_SYSTEM_SLIDER;
    }

    //--------------------------------------------------------------------------
    //
    //  Overridden methods: AccessibilityImplementation
    //
    //--------------------------------------------------------------------------

    /**
     *  @private
     *  Gets the role for the component.
     *
     *  @param childID children of the component
     */
    override public function get_accRole(childID:uint):uint
    {
        var childRole:uint;
        
        switch (childID)
        {
            case 1:
            case 3:
            {
                childRole = AccConst.ROLE_SYSTEM_PUSHBUTTON;
                break;
            }
            case 2:
            {
                childRole = AccConst.ROLE_SYSTEM_INDICATOR;
                break;
            }
            default:
            {
                childRole = role;
                break;
            }
        }
        return childRole;
    }

    //--------------------------------------------------------------------------
    //
    //  Overridden properties: AccImpl
    //
    //--------------------------------------------------------------------------

    //----------------------------------
    //  eventsToHandle
    //----------------------------------

    /**
     *  @private
     *    Array of events that we should listen for from the master component.
     */
    override protected function get eventsToHandle():Array
    {
        return super.eventsToHandle.concat([ "change", FocusEvent.FOCUS_IN]);
    }

    //--------------------------------------------------------------------------
    //
    //  Overridden methods: AccessibilityImplementation
    //
    //--------------------------------------------------------------------------

    /**
     *  @private
     *  IAccessible method for returning the Default Action.
     *
     *  @param childID uint
     *
     *  @return DefaultAction String
     */
    override public function get_accDefaultAction(childID:uint):String
    {
        if (childID == 1 || childID == 3)
            return "Press";
        return null;
    }
    
    /**
     *  @private
     *  IAccessible method for executing the Default Action.
     *
     *  @param childID uint
     */
    override public function accDoDefaultAction(childID:uint):void
    { 
        var slider:SliderBase = SliderBase(master)
        if (childID == 1 && slider.enabled)
            slider.value = slider.value - slider.stepSize;
        else if (childID == 3 && slider.enabled)
            slider.value = slider.value + slider.stepSize;
    }
    
    /**
     *  @private
     *  IAccessible method for returning the bounding box of the Slider or its parts.
     *
     *  @param childID uint
     *
     *  @return Location Object
     */
    override public function accLocation(childID:uint):*
    {
        if (childID == 2)
            return SliderBase(master).thumb;
        // no way to return the parts of the track bar for childID 1 and 3
    }
    /**
     *  @private
     *  IAccessible method for returning the value of the slider
     *  (which would be the value of the item selected).
     *  The slider should return the value of the current thumb as the value.
     *
     *  @param childID uint
     *
     *  @return Value String
     */
    override public function get_accValue(childID:uint):String
    {
        if (childID > 0)
            return null;
        var val:Number = SliderBase(master).value;

        val = (val -  SliderBase(master).minimum) /
              (SliderBase(master).maximum - SliderBase(master).minimum) * 100;

        return String(Math.floor(val));
    }

    /**
     *  @private
     *  Method to return an array of childIDs, which is fixed for sliders.
     * (1 = left/top part of trackbar, 2 = thumb, 3 = right/bottom part of trackbar)
     *
     *  @return Array
     */
    override public function getChildIDArray():Array
    {
        return createChildIDArray(3);
    }

    /**
     *  @private
     *  Method for returning the name of the slider or its sunparts
     *
     *
     *  @param childID uint
     *
     *  @return Name String
     */
    override protected function getName(childID:uint):String
    {
        var resourceManager:IResourceManager = ResourceManager.getInstance();
        var isHSlider:Boolean = 
            getQualifiedClassName(master) == "spark.components::HSlider";
        switch(childID)
        {
            case 1:
                return resourceManager.getString(
                    "components", isHSlider ? 
                    "sliderPageLeftAccName" : "sliderPageDownAccName");
            break;
            case 2:
                return resourceManager.getString(
                    "components", "sliderPositiontAccName");
            break;
            case 3:
                return resourceManager.getString(
                    "components", isHSlider ? 
                    "sliderPageRightAccName" : "sliderPageUpAccName");
            break;
            default:
                return "";
            break;
        }
    }

    /**
     *  @private
     *  IAccessible method for returning the state of the Button.
     *  States are predefined for all the components in MSAA.
     *  Values are assigned to each state.
     *
     *  @param childID uint
     *
     *  @return State uint
     */
    override public function get_accState(childID:uint):uint
    {
        var accState:uint;
        if (childID == 0)
            accState= getState(childID);
        else if (!master.enabled)
            accState = AccConst.STATE_SYSTEM_UNAVAILABLE;
        return accState;
    }

    //--------------------------------------------------------------------------
    //
    //  Overridden event handlers: AccImpl
    //
    //--------------------------------------------------------------------------

    /**
     *  @private
     *  Override the generic event handler.
     *  All AccImpl must implement this to listen
     *  for events from its master component.
     */
    override protected function eventHandler(event:Event):void
    {
        // Let AccImpl class handle the events
        // that all accessible UIComponents understand.
        $eventHandler(event);

        switch (event.type)
        {
            case "change":
            {
                Accessibility.sendEvent(master, 0,
                                        AccConst.EVENT_OBJECT_VALUECHANGE, true);
                break;
            }
            case "focusIn":
                Accessibility.sendEvent(master, 0, AccConst.EVENT_OBJECT_FOCUS);
                break;
        }
    }
}

}
